### ISSUE TITLE
Multiple to Multiple condition

### ISSUE THREAD

**Issue by broom9** [bluebirds-blue-jay/access-control#18]
Sorry for raising a lot of questions. We are seriously using this package :)

I have a use case to verify if an array-type subject attribute and an array-type resource attribute has any overlap. Looking to see what is the best way to achieve it with access-control.

For example: iPhone's TouchID fingerprints. Each person has 10 fingerprints, and each phone can remember 5 fingerprints.

So I was hoping to write a rule like:
```
{
  id: 'unlock',
  action: 'unlock',
  resource: 'phone',
  condition:  {
      arrayOverlap: {
        simpleValue: { 'user.fingerprints': '{{{phone.fingerprints}}}' }
      }
}
```

Here the `arrayOverlap` operator doesn't exist.

I wonder how you see this can be solved, or if it's valuable to add a few array-based operators.

**Comment by SylvainEstevez** [comment]
Haha, no problem @broom9. The documentation is not the greatest, so I'm happy to answer questions. In addition to my responses, I'd suggest you look at AWS IAM policy syntax, as Bluejay uses almost the same syntax (their documentation is quite great).

To answer your question, in order to deal with arrays, look at the `forAnyValue` and `forAllValues` modifiers.

For your example, assuming that your fingerprints are stored as strings:
```
{
  id: 'unlock',
  action: 'unlock',
  resource: 'phone',
  condition:  {
      stringEquals: {
        forAnyValue: { 'user.fingerprints': '{{{phone.fingerprints}}}' }
      }
}
```

The permission above will be valid if for any value in `phone.fingerprints` there exists a value in `user.fingerprints`. Essentially, any overlap between the two arrays will make the condition be true.
