### ISSUE TITLE
Suggestions: Hierarchical Role Based Access Control & more...

### ISSUE THREAD

**Issue by lethak** [bluebirds-blue-jay/access-control#24]
Hi,

I am currently looking for a great JS lib to handle 'Hierarchical Role Based Access Control' or 'HRBAC' and the ones I've found are not so pretty as yours.

1) Do you have plans to support it in the near future ?
2) Do you have any suggestions/workarounds to handle hierarchy in the most efficient way with current version ?

As another suggestion, that would be great to be able to mix exclusion and inclusion in `returnedAttributes` with priority for exclusions by default (configurable maybe ?)

Also, maybe allowing `condition` to be a simple function resolving to true/false could be easier in some cases.

Anyway, thanks for your work.

**Comment by SylvainEstevez** [comment]
Hi @lethak, thank you for the kind words and suggestions.

1. Would you provide me with a practical example of your HRBAC needs, i.e. an example with somes users/roles/permissions? This will help me help you.
2. Mixing whitelist and blacklist in the `returnedAttributes` is kind of evil because it leads to very confusing and/or contradicting settings in my experience. But again, would you provide me with a practical example so that I can assess your needs/possible solutions?
3. I'm not against having the `condition` as a function, it could actually be great. Only issue is that this library makes it possible to store permissions in a database and storing functions would require to use `eval()` when returning from the database.  I guess we could provide this functionality under an `unsafe` configuration flag 🤔

**Comment by SylvainEstevez** [comment]
@lethak Should I close this issue?

**Comment by lethak** [comment]
Hi,
Sorry for the delay, my focus had to shift on other matters, I'll be back on it later, I think you can close this for now since I don't know when I will be back on this, and I'll probably end up creating another lib to handle all our cases anyway.

Thanks for your attention anyway, and sorry to have wasted your time.
